issue-4-delete-an-entry - Ken Kieu
kenkieu/code-journal pull request #9
Opened 2021-09-11 10:19 UTC by kenkieu

Completed issue-4-delete-an-entry.

![issue-4](https://user-images.githubusercontent.com/74282257/132944621-b7ceada6-234e-4edf-973b-53d481ea996f.gif)

2021-09-14 16:24 UTC, codingcodymiller requested changes

2021-09-14 16:24 UTC, codingcodymiller commented on js/main.js
> +      var $entryToDelete = document.querySelector('[data-entry-id]');
Wouldn't this just delete the first entry in the list? What happens if you delete the second entry or one later in the list?

2021-09-15 03:53 UTC, kenkieu commented
Revision for delete feature!

![issue-4-delete-feature-revision](https://user-images.githubusercontent.com/74282257/133368018-b30e0177-91c4-4f78-98a7-9e1e95d89dbe.gif)

2021-09-15 16:41 UTC, codingcodymiller approved these changes

2021-09-15 17:04 UTC, merged